services:
  redis:
    container_name: redis
    restart: on-failure
    image: redis:6.2.6
    ports:
      - 6379:6379
    command: redis-server

  mongodb:
    container_name: mongodb
    restart: on-failure
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./data:/data
    environment:
      MONGODB_INIT_ROOT_USERNAME: ${MONGODB_INIT_ROOT_USERNAME}
      MONGODB_INIT_ROOT_PASSWORD: ${MONGODB_INIT_ROOT_PASSWORD}
      MONGODB_INIT_DATABASE: ${MONGODB_NAME}

  mongo-seed:
    container_name: mongo-seed
    build:
      context: ./
      dockerfile: ./deploy/mongo-seed/Dockerfile
    depends_on:
      - mongodb

  nginx:
    container_name: nginx
    image: nginx:1.18.0
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

  node:
    container_name: node
    restart: on-failure
    build:
      context: ./
      dockerfile: ./deploy/node/Dockerfile

    volumes:
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongodb
