openapi: 3.0.0
info:
  title: 고롱고롱
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0

servers:
  - url: http://www.goronggorong.store/api/v1
    description: Main server
  - url: http://localhost:5000/api/v1
    description: Local server

components:
  # arbitrary name for the security scheme
  securitySchemes:
    RefreshToken:
      type: apiKey
      in: header
      name: X-Refresh-Token
      description: 앞에 bearer를 추가해주세요.
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # /users
  /users:
    $ref: './paths/user.yaml#/paths/~1users'

  # /auth

  /auth/signin:
    $ref: './paths/auth.yaml#/paths/~1auth~1signin'
  /auth/signin/password-reset:
    $ref: './paths/auth.yaml#/paths/~1auth~1signin~1password-reset'
  /auth/validation:
    $ref: './paths/auth.yaml#/paths/~1auth~1validation'
  /auth/tokens:
    $ref: './paths/auth.yaml#/paths/~1auth~1tokens'

  # /products
  /products:
    $ref: './paths/products.yaml#/paths/~1products'
  /products/{id}:
    $ref: './paths/products.yaml#/paths/~1products~1{id}'

  # /orders
  /orders:
    $ref: './paths/orders.yaml#/paths/~1orders'
  /orders/{id}:
    $ref: './paths/orders.yaml#/paths/~1orders~1{id}'
  /orders/{id}/cancellation:
    $ref: './paths/orders.yaml#/paths/~1orders~1{id}~1cancellation'
  /orders/payment:
    $ref: './paths/orders.yaml#/paths/~1orders~1payment'
