openapi: 3.0.0
info:
  title: 고롱고롱
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0

servers:
  - url: http://www.goronggorong.store/api/v1
    description: Main server
  - url: http://localhost:5000/api/v1
    description: Local server

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # /auth
  /auth/signup:
    $ref: './paths/auth.yaml#/paths/~1auth~1signup'
  /auth/signin:
    $ref: './paths/auth.yaml#/paths/~1auth~1signin'
  /auth/signin/password-reset:
    $ref: './paths/auth.yaml#/paths/~1auth~1signin~1password-reset'
  /auth/user-info:
    $ref: './paths/auth.yaml#/paths/~1auth~1user-info'

  # /products
  /products:
    $ref: './paths/products.yaml#/paths/~1products'
  /products/{category}:
    $ref: './paths/products.yaml#/paths/~1products~1{category}'
  /products/{id}:
    $ref: './paths/products.yaml#/paths/~1products'

  # /orders
  /orders/payment:
    $ref: './paths/orders.yaml#/paths/~1orders~1payment'
  /orders/{id}:
    $ref: './paths/orders.yaml#/paths/~1orders~1{id}'
  /orders/cancel/{id}:
    $ref: './paths/orders.yaml#/paths/~1orders~1cancel~1{id}'
  /orders/user/order-list:
    $ref: './paths/orders.yaml#/paths/~1orders~1user~1order-list'
