openapi: 3.0.0
info:
  title: 고롱고롱
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0

servers:
  - url: http://goronggorong.store/api/v1
    description: Main server

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  # /auth
  /auth/signup:
    $ref: './paths/auth.yaml#/paths/~1auth~1signup'
  /auth/signin:
    $ref: './paths/auth.yaml#/paths/~1auth~1signin'
  /auth/signin/password-reset:
    $ref: './paths/auth.yaml#/paths/~1auth~1signin~1password-reset'
  /auth/user-info:
    $ref: './paths/auth.yaml#/paths/~1auth~1user-info'

  # /products
  /:
    $ref: './paths/products.yaml#/paths/~1'
  /products/{category}:
    $ref: './paths/products.yaml#/paths/~1products~1{category}'
  /products:
    $ref: './paths/products.yaml#/paths/~1products'
