services:
  redis:
    container_name: redis
    restart: on-failure
    image: redis:6.2.6
    ports:
      - 6379:6379
    command: redis-server

  nginx:
    container_name: nginx
    image: nginx:1.18.0
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node

  node:
    container_name: node
    restart: on-failure
    build:
      context: ../
      dockerfile: ./deploy/node/Dockerfile
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
