paths:
  /products:
    get:
      tags:
        - products
      summary: 페이지네이션
      description: 구 / router
      parameters:
        - name: category
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: number
        - name: perPage
          in: query
          schema:
            type: number

      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: ${page}페이지의 ${perPage}개의 상품을 불러왔습니다.
                  data:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          $ref: '../components/schemas.yaml#/components/schemas/product'
                      totalProductsAmount:
                        type: number

  /products/{category}:
    get:
      tags:
        - products
      summary: 카테고리별 상품
      description: 페이지네이션 때문에 나중에 /products?category
      deprecated: true

      parameters:
        - name: category
          in: path
          required: true
          description: 카테고리명(Food, Snack, Toy, Toilet, Fashion)
          schema:
            type: string

      responses:
        200:
          $ref: '../components/ok.yaml#/components/schemas/product'

  /products/{id}:
    get:
      tags:
        - products
      summary: 상품 상세 정보
      description: 이전 /products
      parameters:
        - name: id
          in: path
          required: true
          description: 상품 ID
          schema:
            type: string
          example: 1

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 해당 아이디 상품을 불러왔습니다.
                  data:
                    type: object
                    properties:
                      product:
                        $ref: '../components/schemas.yaml#/components/schemas/product'
